# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Release new version'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Package steering Headland extension mod
        run: zip -r -v FS22_FrontBackLiftControl.zip . -x .* .\* Image/\* README.md modBuilder.ps1 modBuilder_test.ps1 modbuilder_test.sh

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Create git tag
        run: git tag $GITVERSION_SEMVER

      - name: Push to repository
        run: git push --tags

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: FS22_FrontBackLiftControl.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.gitversion.outputs.semVer }}

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: FS22_FrontBackLiftControl.zip
